name: adyen_flutter_dropin
description: Flutter plugin to integrate Adyen DropIn UI for Android and iOS.
version: 1.0.1
repository: https://github.com/bschmalb/flutter_adyen_dropin
issue_tracker: https://github.com/bschmalb/flutter_adyen_dropin/issues


environment:
  sdk: '>=2.15.0 <4.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: app.adyen.flutter_adyen
        pluginClass: FlutterAdyenPlugin
      ios:
        pluginClass: FlutterAdyenPlugin

